SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `navigator_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `navigator_db` ;

SET foreign_key_checks = 0;

CREATE TABLE IF NOT EXISTS `navigator_db`.`nodes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `navigator_db`.`vertices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `distance` DOUBLE NOT NULL,
  `source` INT NOT NULL,
  `destination` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vertices_nodes1_idx` (`destination` ASC) VISIBLE,
  INDEX `vertex_source_idx` (`source` ASC) VISIBLE,
  CONSTRAINT `vertex_source`
    FOREIGN KEY (`source`)
    REFERENCES `mydb`.`nodes` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `vertex_destination`
    FOREIGN KEY (`destination`)
    REFERENCES `mydb`.`nodes` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
