SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `navigator_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `navigator_db` ;

CREATE TABLE IF NOT EXISTS `navigator_db`.`nodes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) DEFAULT '' NOT NULL,
  PRIMARY KEY (`id`),
  `vertices_id` INT,
  FOREIGN KEY (`vertices_id`) REFERENCES Vertices(`id`)
			ON DELETE SET NULL,
  UNIQUE INDEX `vertices_id_UNIQUE` (`vertices_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `navigator_db`.`vertices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `source` INT NULL,
  `destination` INT NULL,
  `distance` DECIMAL(5,2) NULL,
  PRIMARY KEY (`id`),
  `node_id` INT,
  FOREIGN KEY (`node_id`) REFERENCES Node(`id`)
			ON DELETE SET NULL,
  UNIQUE INDEX `node_id_UNIQUE` (`node_id` ASC) VISIBLE,
  UNIQUE INDEX `destination_UNIQUE` (`destination` ASC) VISIBLE,
  UNIQUE INDEX `source_UNIQUE` (`source` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;

INSERT INTO vertices (`source`, `destination`) VALUES (`node_id`,`node_id`);
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
